# Generated by Django 4.2.1 on 2023-05-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('category', models.CharField(choices=[('AI(Artificial Intelligence)', 'Ai'), ('ML(Machine Learning)', 'Ml'), ('Graphics/Vfx', 'Graphics')], default='AI(Artificial Intelligence)', max_length=200)),
                ('language', models.CharField(default='JAVA', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
