# Generated by Django 4.2.1 on 2023-05-31 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ratings',
        ),
    ]
