# Generated by Django 4.2.1 on 2023-05-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
