# Generated by Django 4.2.1 on 2023-05-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desription',
            field=models.TextField(default='', max_length=500),
        ),
    ]
