# Generated by Django 4.2.1 on 2023-05-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_desription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='desription',
            new_name='description',
        ),
    ]
