# Generated by Django 4.2.1 on 2023-06-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_desription_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.course')),
            ],
        ),
    ]
