# Generated by Django 4.2.1 on 2023-06-04 13:31

import Django_api.custom_storage.custom_azure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursesimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesimages',
            name='image',
            field=models.ImageField(default='default.jpg', storage=Django_api.custom_storage.custom_azure.AzureMediaStorage, upload_to='media'),
        ),
    ]
