# Generated by Django 4.2.1 on 2023-06-04 13:34

import Django_api.custom_storage.custom_azure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_coursesimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesimages',
            name='image',
            field=models.ImageField(default='default.jpg', storage=Django_api.custom_storage.custom_azure.AzureStaticStorage, upload_to='static'),
        ),
    ]
