# Generated by Django 4.2.1 on 2023-06-17 13:22

import Django_api.custom_storage.custom_azure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_coursesimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesimages',
            name='image',
            field=models.ImageField(default='default.jpg', storage=Django_api.custom_storage.custom_azure.AzureBlobStorage_SAS('nischal.blob.core.windows.net', '?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-06-17T16:20:23Z&st=2023-06-17T08:20:23Z&spr=https&sig=4V1Bi%2F6utwmbrKKwlCxQC4%2BpU5iMPmcDtryrv9F6WaY%3D', 'media'), upload_to='media'),
        ),
    ]
